import {
  AreaChartOutlined,
  DashboardOutlined,
  FileAddOutlined,
  FileProtectOutlined,
  PullRequestOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  UsergroupAddOutlined,
} from '@ant-design/icons';

export const menuItems = [
  {
    key: '1',
    icon: <DashboardOutlined />,
    label: 'Dashboard',
    route: '/dashboard',
    roles: ['user'],
  },
  {
    key: '2',
    icon: <FileAddOutlined />,
    label: 'Add Test',
    route: '/add-test',
    roles: ['admin'],
  },
  {
    key: '3',
    icon: <FileProtectOutlined />,
    label: 'All Tests',
    route: '/all-tests',
    roles: ['admin'],
  },
  {
    key: '4',
    icon: <FileProtectOutlined />,
    label: 'Test',
    route: '/all-tests',
    roles: ['user'],
  },
  {
    key: '5',
    icon: <FileProtectOutlined />,
    label: 'Live Session',
    route: '/live-session',
    roles: ['user'],
  },
 
  {
    key: '6',
    icon: <AreaChartOutlined />,
    label: 'Results',
    route: '/all-results',
    roles: ['admin'],
  },
  {
    key: '7',
    icon: <ScheduleOutlined />,
    label: 'Schedule Webinar',
    route: '/schedule-webinar',
    roles: ['admin'],
  },
  {
    key: '8',
    icon: <PullRequestOutlined />,
    label: 'Session Requests',
    route: '/session-requests',
    roles: ['admin'],
  },
  {
    key: '9',
    icon: <UsergroupAddOutlined />,
    label: 'Management',
    route: '/management',
    roles: ['admin', 'superAdmin'],
  },
  {
    key: '10',
    icon: <ShoppingCartOutlined />,
    label: 'Courses',
    route: '/courses',
    roles: ['admin', 'user'],
  },
  {
    key: '11',
    icon: <SettingOutlined/>,
    label: 'Settings',
    route: '/user-settings',
    roles: ['user'],
  },
  // {
  //   key: '8',
  //   icon: <BookOutlined />,
  //   label: 'View Courses',
  //   route: '/view-courses',
  //   roles: ['admin', 'user'],
  // },
];
