import {
  AreaChartOutlined,
  DashboardOutlined,
  FileAddOutlined,
  FileProtectOutlined,
  PullRequestOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  UsergroupAddOutlined,
} from '@ant-design/icons';

export const menuItems = [
  {
    key: '1',
    icon: <DashboardOutlined />,
    label: 'Dashboard',
    route: '/dashboard',
    activeRoute: ['/dashboard'],
    roles: ['user'],
  },
  {
    key: '2',
    icon: <FileAddOutlined />,
    label: 'Add Test',
    route: '/add-test',
    activeRoute: ['/add-test'],
    roles: ['admin', 'superAdmin'],
  },
  {
    key: '3',
    icon: <FileProtectOutlined />,
    label: 'All Tests',
    route: '/all-tests',
    activeRoute: ['/all-tests'],

    roles: ['admin', 'superAdmin'],
  },
  {
    key: '4',
    icon: <FileProtectOutlined />,
    label: 'Test',
    route: '/tests',
    roles: ['user'],
    activeRoute: ['/tests','/test-results'],
  },
  {
    key: '5',
    icon: <FileProtectOutlined />,
    label: 'Live Session',
    route: '/live-session',
    roles: ['user'],
    activeRoute: ['/live-session'],
  },

  {
    key: '6',
    icon: <AreaChartOutlined />,
    label: 'Results',
    route: '/all-results',
    activeRoute: ['/all-results', '/test-results'],
    roles: ['admin', 'superAdmin'],
  },
  {
    key: '7',
    icon: <ScheduleOutlined />,
    label: 'Schedule Webinar',
    route: '/schedule-webinar',
    activeRoute: ['/schedule-webinar'],
    roles: ['admin', 'superAdmin'],
  },
  {
    key: '8',
    icon: <PullRequestOutlined />,
    label: 'Session Requests',
    route: '/session-requests',
    activeRoute: ['/session-requests'],
    roles: ['admin', 'superAdmin'],
  },
  {
    key: '9',
    icon: <UsergroupAddOutlined />,
    label: 'Management',
    route: '/management',
    activeRoute: ['/management'],
    roles: ['superAdmin'],
  },
  {
    key: '10',
    icon: <ShoppingCartOutlined />,
    label: 'Courses',
    route: '/courses',
    activeRoute: ['/courses', '/view-course'],
    roles: ['admin', 'user', 'superAdmin'],
  },
  {
    key: '11',
    icon: <SettingOutlined />,
    label: 'Settings',
    route: '/user-settings',
    activeRoute: ['/user-settings'],
    roles: ['user'],
  },
  // {
  //   key: '8',
  //   icon: <BookOutlined />,
  //   label: 'View Courses',
  //   route: '/view-courses',
  //   roles: ['admin', 'user'],
  // },
];
